<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.18362.0</TargetFramework>
		<TargetOSVersion>10.0.18362.38</TargetOSVersion>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
		
		<Optimize>true</Optimize>
		<DebugType>pdbonly</DebugType>
		<Prefer32Bit>false</Prefer32Bit>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DefineConstants>TRACE;RELEASE</DefineConstants>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		
		<Version>1.0.0.0</Version>
		<Authors>RomanStalinist, MarkRockord, Sokolovsky-projects, Lexa256</Authors>
		<Company>T-Corporation</Company>
		<Product>TSchedule</Product>
		<PackageId>com.tcorporation.TSchedule</PackageId>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<NeutralLanguage>ru</NeutralLanguage>
		<Description>Программа для ведения расписания в образовательных учреждениях среднего и высшего образований</Description>
		<Copyright>© TCorporation (RomanJava)</Copyright>
		<RepositoryUrl>https://github.com/T-Corporation/TSchedule</RepositoryUrl>
		<RepositoryType>Public</RepositoryType>
		<PackageTags>Scheduling, Education, Timetable, WPF, .NET</PackageTags>
		<PackageIconUrl>Images/favicon.ico</PackageIconUrl>
		<AssemblyName>TSchedule</AssemblyName>
		<ApplicationIcon>Images/favicon.ico</ApplicationIcon>
		
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<OutputType>WinExe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationName>TSchedule</ApplicationName>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Images\admin_375.png" />
	  <None Remove="Images\bell_375.png" />
	  <None Remove="Images\calendar_375.png" />
	  <None Remove="Images\classroom_375.png" />
	  <None Remove="Images\clock_375.png" />
	  <None Remove="Images\faq_375.png" />
	  <None Remove="Images\favicon.ico" />
	  <None Remove="Images\favicon_square.png" />
	  <None Remove="Images\group_375.png" />
	  <None Remove="Images\settings_375.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />
		<PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.9.30" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TSchedule.Persistence\TSchedule.Persistence.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Images\admin_375.png" />
	  <Resource Include="Images\bell_375.png" />
	  <Resource Include="Images\calendar_375.png" />
	  <Resource Include="Images\classroom_375.png" />
	  <Resource Include="Images\clock_375.png" />
	  <Resource Include="Images\faq_375.png" />
	  <Resource Include="Images\group_375.png" />
	  <Resource Include="Images\favicon.ico" />
	  <Resource Include="Images\favicon_square.png" />
	  <Resource Include="Images\settings_375.png" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Preferences.Designer.cs">
	    <DesignTimeSharedInput>True</DesignTimeSharedInput>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Preferences.settings</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Properties\Preferences.settings">
	    <Generator>PublicSettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Preferences.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="ViewModels\Pages\MainWindow\Teachers\" />
	</ItemGroup>

</Project>
